services:
    moop.health.kernel.listener:
        class: Moop\Bundle\HealthBundle\EventListener\CorsKernelListener
        arguments:
            - "@security.token_storage"
            - "@serializer"
            - "@moop.health.cors.response_manager"
            - "@moop.health.security.token_encoder"
            - "@logger"
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 10 }
            - { name: kernel.event_listener, event: kernel.request, method: onRequest, priority: 10 }
            - { name: kernel.event_listener, event: kernel.response, method: onResponse }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelError }
    
    moop.health.service.points:
        class: Moop\Bundle\HealthBundle\Service\PointService
        arguments: ["@event_dispatcher", "@security.token_storage", "%moop.event.points%"]
    
    moop.health.security.token_encoder.basic:
        class: Moop\Bundle\HealthBundle\Security\Encoder\ApiTokenEncoder
    
    moop.health.security.token_encoder.jwt:
        class: Moop\Bundle\HealthBundle\Security\Encoder\JwtTokenEncoder
        arguments:
            - "@moop.health.security.token_helper.hash"
            - "@logger"
    
    moop.health.security.token_helper.hash:
        class: "%moop.health.security.token_helper.hash.class%"
        arguments:
            - "%moop.health.security.token_encoder.algorithm%"
            - false
    
    moop.health.event_listener.points_resolver:
        class: Moop\Bundle\HealthBundle\Event\PointsResolverListener
        arguments: [ "@doctrine", "@moop.health.service.points", "@logger" ]
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
            - { name: kernel.event_listener, event: moop.health.event.points.add, method: onAddPoints }
    
    moop.health.cors.response_manager:
        class: Moop\Bundle\HealthBundle\Service\ResponseManager
        arguments:
            - "@router"
    
    moop.health.user.service:
        class: Moop\Bundle\HealthBundle\Service\UserService
        arguments:
          - "@doctrine"
          - "@moop.fat_secret.api"
          - "@security.encoder_factory"
          - "@logger"
    
    moop.routing.loader:
        class: Moop\Bundle\HealthBundle\Routing\ApiRouteFormatLoader
        tags:
            - { name: routing.loader }

    moop.health.security.firewall.api:
        class: Moop\Bundle\HealthBundle\Security\Firewall\ApiListener
        arguments:
            - "@security.token_storage"
            - "@security.authentication.manager"
            - "@logger"
            - "%moop.user.provider.key%"
            - "%moop.user.provider.algorithm%"
    
    moop.health.security.provider.api:
        class: Moop\Bundle\HealthBundle\Security\Authentication\Provider\ApiProvider
        arguments:
            - "@moop.health.user.service"
            - "@security.password_encoder"
            - "@moop.health.security.token_encoder"
            - "%moop.user.provider.key%"
            - "%moop.user.class%"
            - "%moop.health.security.token_encoder.algorithm%"
            - "@logger"

    moop.health.serialize.normalize:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - name: serializer.normalizer